### PR TITLE
css-gather: Update deps

### PR DESCRIPTION
**Pull request by mlahargou**
This just updates a few of the deps for this repo. Nothing crazy I don't think.

QA:
--
Run through the steps of the README on this repo. Make sure it still works.

Connects: https://github.com/iFixit/ifixit/issues/50016

### CODE REVIEW

**Comment by deltuh-vee** [comment]
dev_block ✊ 
I ran into this error when running `docker-compose build`
CleanShot 2023-11-09 at 12 27 04

**Comment by mlahargou** [comment]
> I ran into this error when running docker-compose build


Are you running this on your local machine or cominor?

**Comment by deltuh-vee** [comment]
@mlahargou I'm running this on my local machine.

**Comment by mlahargou** [comment]
Works fine for me:
image

Does master work for you? Think it might be a problem with your set up.

**Comment by deltuh-vee** [comment]
un_dev_block 👍 
@mlahargou Hmm it worked on main for me. It's also working for me now. Might have been a networking blip.

**Comment by deltuh-vee** [comment]
QA 🎬 
Still able to run `css-gather`.

**Review by batbattur — APPROVED** [review]
CR 🚛

**Pull request merged**
